-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Customers"
(
    id integer NOT NULL,
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Customers_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Manufacturers"
(
    id integer NOT NULL,
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Manufacturers_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Materials"
(
    id integer NOT NULL,
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    code character varying(20) COLLATE pg_catalog."default",
    count numeric(10, 3),
    unit character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT "Materials_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."MaterialsPrices"
(
    id integer NOT NULL,
    material_id integer NOT NULL,
    price money,
    CONSTRAINT "MaterialsPrices_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Orders"
(
    id integer NOT NULL,
    customer_id integer NOT NULL,
    manufacturer_id integer NOT NULL,
    amount money,
    order_date timestamp(0) with time zone,
    CONSTRAINT "Orders_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."OrdersItems"
(
    id integer NOT NULL,
    order_id integer NOT NULL,
    product_id integer NOT NULL,
    count integer,
    unit character varying(20) COLLATE pg_catalog."default",
    price_per_unit money,
    amount money,
    CONSTRAINT "OrdersItems_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Productions"
(
    id integer NOT NULL,
    product_id integer NOT NULL,
    quantity numeric(10, 3),
    status character varying(50) COLLATE pg_catalog."default",
    production_date timestamp(0) with time zone,
    CONSTRAINT "Productions_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Products"
(
    id integer NOT NULL,
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    code character varying(20) COLLATE pg_catalog."default",
    count numeric(10, 3),
    unit character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT "Products_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."ProductsPrices"
(
    id integer NOT NULL,
    product_id integer NOT NULL,
    price money,
    CONSTRAINT "Prices_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Specifications"
(
    id integer NOT NULL,
    product_id integer NOT NULL,
    manufacturer_id integer NOT NULL,
    unit character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT "Specifications_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."SpecificationsMaterials"
(
    id integer NOT NULL,
    specification_id integer NOT NULL,
    material_id integer NOT NULL,
    unit character varying(20) COLLATE pg_catalog."default",
    count numeric(10, 3),
    CONSTRAINT specification_materials_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public."MaterialsPrices"
    ADD CONSTRAINT material_id FOREIGN KEY (material_id)
    REFERENCES public."Materials" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Orders"
    ADD CONSTRAINT customer_id FOREIGN KEY (customer_id)
    REFERENCES public."Customers" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Orders"
    ADD CONSTRAINT manufacturer_id FOREIGN KEY (manufacturer_id)
    REFERENCES public."Manufacturers" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."OrdersItems"
    ADD CONSTRAINT order_id FOREIGN KEY (order_id)
    REFERENCES public."Orders" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."OrdersItems"
    ADD CONSTRAINT product_id FOREIGN KEY (product_id)
    REFERENCES public."Products" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Productions"
    ADD CONSTRAINT product_id FOREIGN KEY (product_id)
    REFERENCES public."Products" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."ProductsPrices"
    ADD CONSTRAINT product_id FOREIGN KEY (product_id)
    REFERENCES public."Products" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Specifications"
    ADD CONSTRAINT manufacturer_id FOREIGN KEY (manufacturer_id)
    REFERENCES public."Manufacturers" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Specifications"
    ADD CONSTRAINT product_id FOREIGN KEY (product_id)
    REFERENCES public."Products" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."SpecificationsMaterials"
    ADD CONSTRAINT material_id FOREIGN KEY (material_id)
    REFERENCES public."Materials" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."SpecificationsMaterials"
    ADD CONSTRAINT specification_id FOREIGN KEY (specification_id)
    REFERENCES public."Specifications" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;